
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: iot-metrics-servicemonitor
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: iot-metrics
  endpoints:
  - port: http
    interval: 15s
  namespaceSelector:
    matchNames:
    - default
